# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuiJiaYou', '0004_grouplunbo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplunbo',
            name='typeid',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
