# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuiJiaYou', '0005_grouplunbo_typeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
